# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/quantum-magnetic-navigation',
                'doc_host': 'https://andreamunafo.github.io',
                'git_url': 'https://github.com/andreamunafo/quantum-magnetic-navigation',
                'lib_path': 'quantum_magnetic_navigation'},
  'syms': { 'quantum_magnetic_navigation.core': { 'quantum_magnetic_navigation.core.foo': ( 'core.html#foo',
                                                                                            'quantum_magnetic_navigation/core.py')}}}
